from pathlib import Path
import base64
import sys
p=Path(sys.argv[1] if len(sys.argv)>1 else 'app/KB911.html')
s=p.read_text(encoding='utf-8')

def rep(a,b,n=1):
    global s
    if a not in s: raise SystemExit('patch_v4 missing fragment: '+a[:100])
    s=s.replace(a,b,n)

# A3 landscape by default and primary image-load button.
rep('<button id="btnImage">Загрузить картинку</button>','<button id="btnImage" class="primary">Загрузить картинку</button>')
rep('<button data-tool="text">Добавить надпись</button>','<button data-tool="text">Добавить надпись</button>\n  <button data-tool="leader">Сноска</button>')
rep('<select id="paperSize"><option selected>A4</option><option>A3</option>','<select id="paperSize"><option>A4</option><option selected>A3</option>')

# Donation is its own module below the frame description; handshake instead of heart.
old='<div id="donateWrap"><button id="donateBtn">♥ Попрошайка ▾</button><div id="donateMenu"><button type="button">Варианты поддержки добавим позже</button></div></div>\n    <div class="hint">Контур 0,3 мм, отступ от края листа 5 мм. Название и логотип можно включать независимо.</div>'
new='<div class="hint">Контур 0,3 мм, отступ от края листа 5 мм. Название и логотип можно включать независимо.</div>\n  </div>\n  <div class="group" id="donateModule"><div id="donateWrap"><button id="donateBtn" type="button" aria-expanded="false"><img src="__KB911_DONATE_ICON__" alt="">Попрошайка ▾</button><div id="donateMenu">Если Вам понравилось что я сделал, если Вам действительно помогает в работе эта бесплатная утилита, буду благодарен любой сумме в качестве безвозмездной помощи ))) советы и пожелания по улучшению готов принять по электронной почте (можно скопировать нажав на название программы), СПАСИБО за Ваше участие!</div><div id="donateQrArea"><img id="donateQrImage" src="__KB911_DONATE_QR__" alt="QR-код для перевода через Т-Банк или Сбербанк"></div></div>'
rep(old,new)
for placeholder, path in [('__KB911_DONATE_ICON__',Path('assets/donate_icon.png')),('__KB911_DONATE_QR__',Path('assets/donate_qr.png'))]:
    if s.count(placeholder)!=1: raise SystemExit('donation image placeholder missing: '+placeholder)
    s=s.replace(placeholder,'data:image/png;base64,'+base64.b64encode(path.read_bytes()).decode('ascii'),1)
# close donate module before aside closes
rep('  </div>\n</aside>\n</main>','  </div>\n</aside>\n</main>',1)

# Text settings: italic + border.
rep('<div class="tp-full tp-checks"><label><input id="textBold" type="checkbox" checked> Жирный</label></div>','<div class="tp-full tp-checks"><label><input id="textBold" type="checkbox" checked> Жирный</label><label><input id="textItalic" type="checkbox"> Курсив</label><label><input id="textBorder" type="checkbox"> Обводка поля</label></div>')
rep("const builtText={font:'Bahnschrift',fontSize:'4',textColor:'#111111',bg:'#ffffff',bgOpacity:'0',bold:true,angle:'0',align:'center'};","const builtText={font:'Bahnschrift',fontSize:'4',textColor:'#111111',bg:'#ffffff',bgOpacity:'0',bold:true,italic:false,border:false,angle:'0',align:'center'};")
rep("'data-bold':d.bold?'1':'0','data-angle':d.angle||'0'","'data-bold':d.bold?'1':'0','data-italic':d.italic?'1':'0','data-border':d.border?'1':'0','data-angle':d.angle||'0'")
rep("fill:g.dataset.bg||'#fff','fill-opacity':g.dataset.bgOpacity||0,stroke:'none'","fill:g.dataset.bg||'#fff','fill-opacity':g.dataset.bgOpacity||0,stroke:g.dataset.border==='1'?(g.dataset.textColor||'#111'):'none','stroke-width':g.dataset.border==='1'?'.35':'0'")
rep("'font-weight':g.dataset.bold==='1'?'700':'400',fill:g.dataset.textColor||'#111'","'font-weight':g.dataset.bold==='1'?'700':'400','font-style':g.dataset.italic==='1'?'italic':'normal',fill:g.dataset.textColor||'#111'")
rep("$('textBold').checked=g.dataset.bold==='1';$('textAngle').value", "$('textBold').checked=g.dataset.bold==='1';$('textItalic').checked=g.dataset.italic==='1';$('textBorder').checked=g.dataset.border==='1';$('textAngle').value")
rep("$('textBold').addEventListener('change',()=>{if(selected?.dataset.type!=='text')return;selected.dataset.bold=$('textBold').checked?'1':'0';renderText(selected);drawSelection()});", "[['textBold','bold'],['textItalic','italic'],['textBorder','border']].forEach(([id,key])=>$(id).addEventListener('change',()=>{if(selected?.dataset.type!=='text')return;selected.dataset[key]=$(id).checked?'1':'0';renderText(selected);drawSelection()}));")
rep("ctx.font=`${g.dataset.bold==='1'?'700':'400'} ${fs}px ${font}`;", "ctx.font=`${g.dataset.italic==='1'?'italic ':''}${g.dataset.bold==='1'?'700':'400'} ${fs}px ${font}`;")
rep("const opa=+(g.dataset.bgOpacity||0);if(opa>0){", "const opa=+(g.dataset.bgOpacity||0);if(g.dataset.border==='1'){ctx.strokeStyle=g.dataset.textColor||'#111';ctx.lineWidth=.35;roundedRectPath(ctx,x,y,w,h,2.5);ctx.stroke()}if(opa>0){")

# Leader popup UI and CSS.
rep('#dimPopup,#textPopup{', '#dimPopup,#textPopup,#leaderPopup{')
rep('#dimPopup.open,#textPopup.open{display:block}', '#dimPopup.open,#textPopup.open,#leaderPopup.open{display:block}')
rep('</div>\n</div>\n<script>\n(()=>{', '''</div>\n</div>\n<div id="leaderPopup" aria-hidden="true" style="position:fixed;z-index:45;width:320px;background:#f7f7f8;border:1px solid #9b9ba0;border-radius:7px;box-shadow:0 14px 40px rgba(0,0,0,.24);display:none;overflow:hidden">\n <div id="leaderPopupHeader" style="height:32px;display:flex;align-items:center;padding:0 9px;background:#fff;border-bottom:1px solid #d5d5da;cursor:move;font-weight:600">Сноска <span style="flex:1"></span><button id="leaderPopupClose" class="mini">×</button></div>\n <div style="padding:9px">\n  <div class="label">Текст</div><input id="leaderText" type="text" style="width:100%">\n  <div class="row"><div style="flex:1"><div class="label">Полка, мм</div><input id="leaderShelf" type="number" min="8" max="500" step="1" value="40" style="width:100%"></div><div style="flex:1"><div class="label">Шрифт, мм</div><input id="leaderFontSize" type="number" min="1.5" max="30" step="0.5" value="4" style="width:100%"></div></div>\n  <div class="tp-checks" style="margin-top:8px"><label><input id="leaderBold" type="checkbox" checked> Жирный</label><label><input id="leaderItalic" type="checkbox"> Курсив</label></div>\n  <div class="tp-actions"><button id="leaderOk" class="primary">OK</button></div>\n </div>\n</div>\n<script>\n(()=>{''')

# Leader state.
rep('let dimDraft=null,dimPreview=null,textDraft=null,textPreview=null,drag=null,', 'let dimDraft=null,dimPreview=null,textDraft=null,textPreview=null,leaderDraft=null,leaderPreview=null,leaderDrag=null,drag=null,')

# setTool leader status.
rep("else if(tool==='text')setStatus('Надпись: растяните область будущего текста');else if(!tool)", "else if(tool==='text')setStatus('Надпись: растяните область будущего текста');else if(tool==='leader')setStatus('Сноска: поставьте точку стрелки и протяните к началу полки');else if(!tool)")

# Leader functions inserted before moveImageLayer.
anchor='function moveImageLayer(img,where)'
leader_js=r'''function leaderPts(g){const p1=parsePt(g.dataset.p1),p2=parsePt(g.dataset.p2),dir=(+g.dataset.dir||1),shelf=+g.dataset.shelf||40,p3={x:p2.x+dir*shelf,y:p2.y};return{p1,p2,p3,dir,shelf}}\nfunction renderLeader(g){while(g.firstChild)g.removeChild(g.firstChild);const{p1,p2,p3,dir}=leaderPts(g),c=dimDefaults.lineColor||'#111',lw=+dimDefaults.lineWidth||.4,as=+dimDefaults.arrowSize||5,aa=+dimDefaults.arrowAngle||10,sty=dimDefaults.arrow||'slim';g.appendChild(el('line',{x1:p1.x,y1:p1.y,x2:p2.x,y2:p2.y,stroke:c,'stroke-width':lw,'vector-effect':'non-scaling-stroke'}));g.appendChild(el('line',{x1:p2.x,y1:p2.y,x2:p3.x,y2:p3.y,stroke:c,'stroke-width':lw,'vector-effect':'non-scaling-stroke'}));const ux=(p2.x-p1.x)/(Math.hypot(p2.x-p1.x,p2.y-p1.y)||1),uy=(p2.y-p1.y)/(Math.hypot(p2.x-p1.x,p2.y-p1.y)||1);drawArrow(g,p1,ux,uy,as,aa,c,lw,1,sty);const fs=+g.dataset.fontSize||4,t=el('text',{x:(p2.x+p3.x)/2,y:p2.y-fs*.8,'text-anchor':'middle','dominant-baseline':'central','font-family':'Bahnschrift','font-size':fs,'font-weight':g.dataset.bold==='1'?'700':'400','font-style':g.dataset.italic==='1'?'italic':'normal',fill:c});t.textContent=g.dataset.value||'Сноска';g.appendChild(t);g.appendChild(el('path',{d:`M ${p1.x} ${p1.y} L ${p2.x} ${p2.y} L ${p3.x} ${p3.y}`,fill:'none',stroke:'transparent','stroke-width':6,class:'leader-hit'}))}\nfunction drawLeaderHandles(g){const{p1,p2,p3}=leaderPts(g);[['p1',p1],['p2',p2],['p3',p3]].forEach(([k,p])=>paper.appendChild(el('circle',{cx:p.x,cy:p.y,r:.8,class:'handle selection-ui leader-handle','data-owner':g.dataset.id,'data-leader-handle':k})))}\nfunction createLeader(p1,p2){const dir=p2.x>=p1.x?1:-1,g=el('g',{'data-type':'leader','data-id':uid++,'data-p1':`${p1.x},${p1.y}`,'data-p2':`${p2.x},${p2.y}`,'data-dir':dir,'data-shelf':'40','data-value':'Сноска','data-font-size':'4','data-bold':'1','data-italic':'0'});appendContent(g);renderLeader(g);selected=g;drawSelection();openLeaderPopup(g)}\nfunction openLeaderPopup(g){selected=g;$('leaderText').value=g.dataset.value||'';$('leaderShelf').value=g.dataset.shelf||40;$('leaderFontSize').value=g.dataset.fontSize||4;$('leaderBold').checked=g.dataset.bold==='1';$('leaderItalic').checked=g.dataset.italic==='1';const p=$('leaderPopup');p.style.display='block';p.classList.add('open');p.style.left=Math.max(10,(innerWidth-320)/2)+'px';p.style.top=Math.max(60,(innerHeight-260)/2)+'px'}\nfunction closeLeaderPopup(){const p=$('leaderPopup');p.classList.remove('open');p.style.display='none'}\n'''
rep(anchor, leader_js+anchor)

# Selection draws leader handles.
rep("if(selected.dataset.type==='image'){drawImageHandles(selected);return}}", "if(selected.dataset.type==='image'){drawImageHandles(selected);return}if(selected.dataset.type==='leader'){drawLeaderHandles(selected);return}}")

# Capture-phase leader interaction so existing handlers do not interfere.
insert="""\npaper.addEventListener('pointerdown',e=>{const p=pt(e),obj=groupType(e.target);if(tool==='leader'&&!obj){e.preventDefault();e.stopImmediatePropagation();leaderDraft={p1:p,p2:p};leaderPreview=el('path',{d:`M ${p.x} ${p.y} L ${p.x} ${p.y}`,fill:'none',stroke:'#2563eb','stroke-width':'.5','stroke-dasharray':'2 1'});paper.appendChild(leaderPreview);return}if(e.target.classList?.contains('leader-handle')){const g=findOwner(e.target.dataset.owner,'leader');if(g){selected=g;leaderDrag={obj:g,kind:e.target.dataset.leaderHandle,start:p,p1:parsePt(g.dataset.p1),p2:parsePt(g.dataset.p2),shelf:+g.dataset.shelf||40};e.preventDefault();e.stopImmediatePropagation();return}}if(obj?.dataset.type==='leader'){selected=obj;drawSelection();leaderDrag={obj,start:p,kind:'move',p1:parsePt(obj.dataset.p1),p2:parsePt(obj.dataset.p2)};e.preventDefault();e.stopImmediatePropagation()}},true);\npaper.addEventListener('pointermove',e=>{const p=pt(e);if(leaderDraft&&tool==='leader'){leaderDraft.p2=p;const dir=p.x>=leaderDraft.p1.x?1:-1,p3x=p.x+dir*40;leaderPreview.setAttribute('d',`M ${leaderDraft.p1.x} ${leaderDraft.p1.y} L ${p.x} ${p.y} L ${p3x} ${p.y}`);e.stopImmediatePropagation();return}if(!leaderDrag)return;const d=leaderDrag,g=d.obj;if(d.kind==='move'){const dx=p.x-d.start.x,dy=p.y-d.start.y;g.dataset.p1=`${d.p1.x+dx},${d.p1.y+dy}`;g.dataset.p2=`${d.p2.x+dx},${d.p2.y+dy}`}else if(d.kind==='p1')g.dataset.p1=`${p.x},${p.y}`;else if(d.kind==='p2'){g.dataset.p2=`${p.x},${p.y}`;g.dataset.dir=p.x>=parsePt(g.dataset.p1).x?'1':'-1'}else if(d.kind==='p3'){const p2=parsePt(g.dataset.p2),dir=+g.dataset.dir||1;g.dataset.shelf=String(Math.max(8,Math.abs(p.x-p2.x)));g.dataset.dir=p.x>=p2.x?'1':'-1'}renderLeader(g);drawSelection();e.stopImmediatePropagation()},true);\nwindow.addEventListener('pointerup',e=>{if(leaderDraft&&tool==='leader'){const p2=pt(e),p1=leaderDraft.p1;leaderDraft=null;leaderPreview?.remove();leaderPreview=null;if(Math.hypot(p2.x-p1.x,p2.y-p1.y)>2)createLeader(p1,p2)}leaderDrag=null},true);\npaper.addEventListener('dblclick',e=>{const obj=groupType(e.target);if(obj?.dataset.type==='leader'){e.preventDefault();e.stopImmediatePropagation();openLeaderPopup(obj)}},true);\n"""
rep("paper.addEventListener('pointerdown',e=>{const p=pt(e),obj=groupType(e.target);", insert+"paper.addEventListener('pointerdown',e=>{const p=pt(e),obj=groupType(e.target);",1)

# Popup listeners.
rep("$('donateBtn').onclick=", "$('leaderText').oninput=()=>{if(selected?.dataset.type==='leader'){selected.dataset.value=$('leaderText').value;renderLeader(selected);drawSelection()}};$('leaderShelf').oninput=()=>{if(selected?.dataset.type==='leader'){selected.dataset.shelf=$('leaderShelf').value;renderLeader(selected);drawSelection()}};$('leaderFontSize').oninput=()=>{if(selected?.dataset.type==='leader'){selected.dataset.fontSize=$('leaderFontSize').value;renderLeader(selected);drawSelection()}};$('leaderBold').onchange=()=>{if(selected?.dataset.type==='leader'){selected.dataset.bold=$('leaderBold').checked?'1':'0';renderLeader(selected);drawSelection()}};$('leaderItalic').onchange=()=>{if(selected?.dataset.type==='leader'){selected.dataset.italic=$('leaderItalic').checked?'1':'0';renderLeader(selected);drawSelection()}};$('leaderPopupClose').onclick=closeLeaderPopup;$('leaderOk').onclick=()=>{closeLeaderPopup();clearSelection();setTool(null,true);setStatus('Сноска зафиксирована')};\n$('donateBtn').onclick=")

# Export leaders as SVG-like dimension objects.
rep("else if(n.matches?.('g[data-type=\"text\"]'))drawTextObject(ctx,n);else if(n.matches?.('g[data-type=\"frame\"]'))", "else if(n.matches?.('g[data-type=\"text\"]'))drawTextObject(ctx,n);else if(n.matches?.('g[data-type=\"leader\"]'))drawDimensionObject(ctx,n);else if(n.matches?.('g[data-type=\"frame\"]'))")

p.write_text(s,encoding='utf-8',newline='')
print('KB911 v4 patch applied',len(s.encode('utf-8')))
